version: "3.9"

networks:
  proxy:
    external: true
  backend:
    external: false

volumes:
  postgres:
  postgres-backups:

services:
  postgres:
    # Image tags
    image: postgres:13.4
    container_name: postgres
    networks:
      - backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - postgres:/var/lib/postgresql/data:rw
    environment:
      # Database name
      POSTGRES_DB: zabbixdb
      # Database user
      POSTGRES_USER: zabbixdbuser
      # Database password
      POSTGRES_PASSWORD: FmuHw92hiFZfJNzKvzgNwsf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  zabbix:
    # Image tags
    image: zabbix-server-pgsql-build:ubuntu-5.4.8
    container_name: zabbix
    networks:
      - backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./data/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./data/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./data/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./data/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./data/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./data/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - ./data/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      # Database name
      POSTGRES_DB: zabbixdb
      # Database user
      POSTGRES_USER: zabbixdbuser
      # Database password
      POSTGRES_PASSWORD: FmuHw92hiFZfJNzKvzgNwsf
      ZBX_STARTPOLLERS: 100
      ZBX_STARTPOLLERSUNREACHABLE: 50
      ZBX_STARTPINGERS: 50
      ZBX_STARTTRAPPERS: 10
      ZBX_STARTDISCOVERERS: 15
      ZBX_STARTPREPROCESSORS: 15
      ZBX_STARTHTTPPOLLERS: 5
      ZBX_STARTALERTERS: 5
      ZBX_STARTTIMERS: 2
      ZBX_STARTESCALATORS: 2
      ZBX_HISTORYCACHESIZE: 64M
      ZBX_HISTORYINDEXCACHESIZE: 32M
      ZBX_VALUECACHESIZE: 64M
      ZBX_CACHESIZE: 128M
      ZBX_TRENDCACHESIZE: 128M
      ZBX_TIMEOUT: 30
    ports:
      - "10051:10051"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  web:
    # Image tags
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-5.4.8
    container_name: web
    networks:
      - proxy
      - backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      # Database name
      POSTGRES_DB: zabbixdb
      # Database user
      POSTGRES_USER: zabbixdbuser
      POSTGRES_PASSWORD: FmuHw92hiFZfJNzKvzgNwsf
      ZBX_SERVER_HOST: zabbix
      ZBX_SERVER_PORT: 10051
      ZBX_SERVER_NAME: Zabbix-Monitor-VDC
      # Timezone
      PHP_TZ: Asia/Ho_Chi_Minh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.zabbix.entrypoints=websecure"
      - "traefik.http.routers.zabbix.rule=Host(`monitormail-vdc.matbao.io`)"
      - "traefik.http.routers.zabbix.tls=true"
      - "traefik.http.routers.zabbix.service=zabbix"
      - "traefik.http.services.zabbix.loadbalancer.server.port=8080"
      - "traefik.http.routers.zabbix.middlewares=secured@file"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  agent2:
    # Image tag
    image: zabbix/zabbix-agent2:ubuntu-5.4.8
    container_name: agent2
    privileged: true
    networks:
      - backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./data/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./data/var/lib/zabbix/buffer:/var/lib/zabbix/buffer:ro
    environment:
      # Zabbix Hostname (replace with yours)
      # Set as DNS name on Zabbix server host configuration screen to make checks of Zabbix server itself
      ZBX_HOSTNAME: monitormail-vdc.matbao.io
      ZBX_SERVER_HOST: 0.0.0.0/0
      # Encryption 
      ZBX_TLSCONNECT: psk
      ZBX_TLSACCEPT: psk
      ZBX_TLSPSKIDENTITY: MONITOR-VDC-PSK
      ZBX_TLSPSKFILE: /var/lib/zabbix/enc/agent.psk 
    ports:
      - "10050:10050"
    restart: unless-stopped
    depends_on:
      - postgres
      - zabbix

  backups:
    # Image tags
    image: postgres:13.4
    container_name: postgres_backups
    # Database backups prune interval (replace with yours). Default is 7 days.
    # find /srv/zabbix-postgres/backups -type f -mtime +7 | xargs rm -f

    # Zabbix backups interval (replace with yours). Default is 1 day.
    # sleep 24h
  
    # Run zabbix-restore-database.sh to restore database if needed.
    command: sh -c 'sleep 30m
             && while true; do
             PGPASSWORD="$$(echo $$POSTGRES_PASSWORD)"
             pg_dump
             -h postgres
             -p 5432
             -d zabbixdb
             -U zabbixdbuser | gzip > /srv/zabbix-postgres/backups/zabbix-postgres-backup-$$(date "+%Y-%m-%d_%H-%M").gz
             && find /srv/zabbix-postgres/backups -type f -mtime +7 | xargs rm -f;
             sleep 24h; done'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Database backups location
      - postgres-backups:/srv/zabbix-postgres/backups
    environment:
      # Database password
      POSTGRES_PASSWORD: FmuHw92hiFZfJNzKvzgNwsf
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      web:
        condition: service_healthy
